name: update-http-csv

on:
  schedule:
    - cron:  '0 4 * * *'

# This job installs dependencies, build the book, and pushes it to `gh-pages`
jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    
    - name: Run script to add numbers csv file
      run: python record_http_stats.py

    - name: GitHub Pages action
      uses: peaceiris/actions-gh-pages@v3.6.1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./
