name: update-http-csv

on:
  workflow_dispatch:
  push:
    branches:
    - gh-pages

# This job installs dependencies, build the book, and pushes it to `gh-pages`
jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: some-branch

    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    
    - name: Run script to add numbers csv file
      run: python record_http_stats.py

    - name: push updated csv file to main branch
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Auto update orgs_http_stats.csv file
        branch: http-count-log
